version: '3.4'

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build: 
     context: .
     dockerfile: Gateway/Dockerfile
    container_name: gateway
    ports:
      - '8080:80'
    depends_on:
      - service-advertisement
      - service-user
    networks:
      - lplace-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
        RABBITMQ_DEFAULT_USER: sa
        RABBITMQ_DEFAULT_PASS: admin
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - lplace-network

  db-advertisement:
    image: "mcr.microsoft.com/mssql/server"
    container_name: db-advertisement
    environment:
        SA_PASSWORD: "My_password123"
        ACCEPT_EULA: "Y"
    networks:
      - lplace-network
    ports:
      - "1434:1433"
    volumes:
      - database-data-advertisement:/var/opt/mssql

  service-advertisement:
    image: ${DOCKER_REGISTRY-}serviceadvertisement
    container_name: service-advertisement
    build:
      context: .
      dockerfile: Service-Advertisement/Dockerfile
    environment:
      PRODUCTION: "false"
      RABBITMQ_USERNAME: sa
      RABBITMQ_PASSWORD: admin
      DATABASE_SERVER: db-advertisement
      DATABASE_PASSWORD: My_password123
      DATABASE_PORT: "1433"
    ports:
      - '8082:80'
    depends_on:
      - db-advertisement
      - rabbitmq
    networks:
      - lplace-network

  db-user:
    image: "mcr.microsoft.com/mssql/server"
    container_name: db-user
    environment:
        SA_PASSWORD: "My_Other_password123"
        ACCEPT_EULA: "Y"
    networks:
      - lplace-network
    ports:
      - "1433:1433"
    volumes:
      - database-data-user:/var/opt/mssql

  service-user:
    image: ${DOCKER_REGISTRY-}serviceuser
    container_name: service-user
    build:
      context: .
      dockerfile: Service-User/Dockerfile
    environment:
        PRODUCTION: "false"
        RABBITMQ_USERNAME: sa
        RABBITMQ_PASSWORD: admin
        DATABASE_SERVER: db-user
        DATABASE_PASSWORD: My_Other_password123
        DATABASE_PORT: "1433"
    ports:
      - '8084:80'
    depends_on:
      - db-user
      - rabbitmq
    networks:
      - lplace-network



volumes:
    database-data-user:
    database-data-advertisement:

networks:
  lplace-network:
    driver: bridge