apiVersion: apps/v1
kind: Deployment
metadata:
  name: advertisement-mssql-deployment
  namespace: lplace
spec:
  replicas: 1
  selector:
     matchLabels:
       app: db-advertisement
  template:
    metadata:
      labels:
        app: db-advertisement
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: db-advertisement
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Express"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-advertisement
              key: SA_PASSWORD 
        volumeMounts:
        - name: advertisement-mssql-db
          mountPath: /var/opt/mssql
      volumes:
      - name: advertisement-mssql-db
        persistentVolumeClaim:
          claimName: advertisement-database-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-advertisement
  namespace: lplace
spec:
  selector:
    app: db-advertisement
  ports:
    - name: db-advertisement
      protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP