kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: advertisement-database-volume-claim
  namespace: lplace
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi