apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: lplace
  name: advertisement-mssql-sfs
spec:
  selector:
    matchLabels:
      app: db-advertisement
  serviceName: "db-advertisement"
  replicas: 2 
  template:
    metadata:
      labels:
        app: db-advertisement
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 10001
      containers:
      - name: db-advertisement
        image:  mcr.microsoft.com/mssql/server:2019-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-advertisement
              key: SA_PASSWORD
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: data
          mountPath: /var/opt/mssql/data
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: azure-disk
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: azure-disk
      resources:
        requests:
          storage: 1Gi