apiVersion: apps/v1
kind: Deployment
metadata:
  name: advertisement-deployment
  namespace: lplace
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: service-advertisement
  template:
    metadata:
      labels:
        app: service-advertisement
    spec:
      hostname: service-advertisement
      containers:
        - name: service-advertisement
          image: ghcr.io/luukdekinderen/lplace/service-advertisement:main
          imagePullPolicy: Always
          env:
          - name: PRODUCTION
            value: "TRUE"
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: RABBITMQ_USERNAME
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: RABBITMQ_PASSWORD
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-advertisement
                key: SA_PASSWORD
          - name: DATABASE_SERVER
            value: db-advertisement
          - name: DATABASE_PORT
            value: "1433"
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: 50Mi
              cpu: 500m
            limits:
              memory: 500Mi
              cpu: 2000m
            
---

apiVersion: v1
kind: Service
metadata:
  name: service-advertisement
  namespace: lplace
  labels:
    app: service-advertisement
spec:
  ports:
  - port: 80
  selector:
    app: service-advertisement

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: advertisement-autoscaler
  namespace: lplace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: advertisement-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75  
