apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: lplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: RABBITMQ_USERNAME
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: RABBITMQ_PASSWORD
          ports:
            - containerPort: 15672
              name: rbmq-man-port
            - containerPort: 5672
              name: rbmq-mess-port
          volumeMounts:
          - name: rabbitmq-claim
            mountPath: "/var/lib/rabbitmq/mnesia"
      volumes:
      - name: rabbitmq-claim
        persistentVolumeClaim:
          claimName: rabbitmq-claim

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: rbmq-mess-port
    protocol: TCP
    port: 5672
    targetPort: 5672

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-loadbalancer-srv
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
  - name: rbmq-man-port
    protocol: TCP
    port: 15672
    targetPort: 15672