apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-claim
  namespace: lplace
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi