apiVersion: v1
kind: Service
metadata:
  name: advertismentnpservice-srv
spec:
  type: NodePort
  selector:
    app: service-advertisement
  ports:
    - name: service-advertisement
      protocol: TCP
      port: 80
      targetPort: 80