apiVersion: apps/v1
kind: Deployment
metadata:
  name: advertisement-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-advertisement
  template:
    metadata:
      labels:
        app: service-advertisement
    spec:
      containers:
        - name: service-advertisement
          image: ghcr.io/luukdekinderen/lplace/service-advertisement:main

---

apiVersion: v1
kind: Service
metadata:
  name: service-advertisement
spec:
  type: ClusterIP
  selector:
    app: service-advertisement
  ports:
  - name: service-advertisement
    protocol: TCP
    port: 80
    targetPort: 80