apiVersion: v1
kind: Service
metadata:
  name: gatewaynpservice-srv
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: gateway
      protocol: TCP
      port: 80
      targetPort: 80