apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ghcr.io/luukdekinderen/lplace/gateway:main

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  # type: ClusterIP
  selector:
    app: gateway
  ports:
  - name: gateway
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer