
#this is the secret for the MSSQL db, pointing to the password to use for the SA account
apiVersion: v1
kind: Secret
metadata:
  name: mssql
  namespace: plantr
type: Opaque
stringData:
  SA_PASSWORD: "Your_password123" 
---