apiVersion: v1
kind: Service
metadata:
  name: lplace-service-user
  namespace: lplace
  labels:
    app: lplace-service-user
    service: lplace-service-user
spec: 
  selector:
    app: lplace-service-user-pod
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
  type: LoadBalancer  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lplace-service-user
  namespace: lplace
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: lplace-service-user-pod
      version: latest   
  template:
    metadata:
      labels:
        app: lplace-service-user-pod
        version: latest
    spec:
      hostname: service-user
      containers:
        - name: lplace-user-container
          image: ghcr.io/luukdekinderen/lplace/service-user:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: service-user
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lplace-service-user-autoscaler
  namespace: lplace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lplace-service-user
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75