apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: lplace
spec:
  replicas: 1
  image: rabbitmq:3-management-alpine
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    volumeMounts:
    - name: lplace-rabbitmq-volume-lib
    mountPath: /var/lib/rabbitmq/
    - name: lplace-rabbitmq-volume-log
    mountPath: /var/log/rabbitmq
  volumes:
    - name: lplace-rabbitmq-volume-lib
      persistentVolumeClaim:
        claimName: lplace-rabbitmq-volume-claim
    - name: lplace-rabbitmq-volume-log
      persistentVolumeClaim:
        claimName: lplace-rabbitmq-volume-claim