apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lplace-rabbitmq-volume-claim
  namespace: lplace
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-premium