name: Test Advertisement Service

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: ./Service-Advertisement-Test
      run: dotnet restore
    - name: Build
      working-directory: ./Service-Advertisement-Test
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./Service-Advertisement-Test
      run: dotnet test --no-build --verbosity normal
